name: practice Github Action workflow

on: [push]

jobs:
  practice-github-job:
    runs-on: ubuntu-latest
    steps:
      - name: printing steps name
        run: echo "Welcome to Practice git hub"
  checkout-github-job:
    runs-on: ubuntu-latest
    steps:
      - name: check directory & print in-build enviroinment values
        run : |
          pwd
          ls -lrt
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: Cloning our source code here
        uses: actions/checkout@v2
        with:
          ref: conekt
      - name: Printing directory
        run: |
          pwd
          ls -a
          ls -lrt
          git branch